#!/bin/bash
shopt -s expand_aliases
source ~/.bashrc
emsdk_setup > /dev/null

set -e

emcc "$1" -std=c++11 -g -Os -o "$2.wasm" -s NO_EXIT_RUNTIME=1 -s ERROR_ON_UNDEFINED_SYMBOLS=0
wasm2wat "$2.wasm" -o "$2"
rm "$2.wasm"
python3 sub_primitives.py "$2"
