#!/bin/bash

clang -O2 -c ../wasmtime/wasmtime-runtime/conts/conts.c -o libs/conts.o
clang -O2 -c ../wasmtime/wasmtime-runtime/src/continuations.s -o libs/continuations.o
clang++ -O2 -std=c++11 "$@" libs/conts.o libs/continuations.o -o a.out
