#!/bin/bash
shopt -s expand_aliases
source ~/.bash_aliases
emsdk_setup > /dev/null

set -e

out_arg=${@:$#} # last parameter 
in_args=${*%${!#}} # all parameters except the last

emcc $in_args -std=c++11 -g -Os -o "$out_arg.wasm" -s NO_EXIT_RUNTIME=1 -s ERROR_ON_UNDEFINED_SYMBOLS=0
wasm2wat "$out_arg.wasm" -o "$out_arg"
rm "$out_arg.wasm"
sub_primitives.py "$out_arg"
