#!/bin/bash
shopt -s expand_aliases
source ~/.bashrc
# emsdk_setup > /dev/null

set -e

out_arg=${@:$#} # last parameter 
in_args=${*%${!#}} # all parameters except the last

wasicc $in_args -g -Oz -o "$out_arg.wasm" --for-linker=--allow-undefined
wasm2wat "$out_arg.wasm" -o "$out_arg"
rm "$out_arg.wasm"
sub_primitives.py "$out_arg"
