#ifndef _CONFIG_H
#define _CONFIG_H

// #define TIME_YIELD 1

#define WASMTIME_CONTS 1
#define WASMTIME_ASYNCIFY 2
#define NATIVE_SWAPCONTEXT 3
#define NATIVE_PTHREAD 4
#define NATIVE_SERIAL 5
#define WASMTIME_SERIAL 6

#define NEED_CONTEXT ((CONTEXT_IMPL == WASMTIME_CONTS) || (CONTEXT_IMPL == WASMTIME_ASYNCIFY) || (CONTEXT_IMPL == NATIVE_SWAPCONTEXT))

#endif
